/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface PhpRequestOptions {
  method?: string
  url?: string
  body?: string
}
export interface PhpOptions {
  code: string
  file?: string
}
export type PhpRequest = Request
export declare class Request {
  constructor(options?: PhpRequestOptions | undefined | null)
  get method(): string
  get url(): string
  get body(): string
}
export declare class Php {
  options: PhpOptions
  constructor(options: PhpOptions)
  handleRequest(request: Request): Promise<unknown>
}
export declare class PhpResponse {
  get status(): number
  get body(): string
}
