[package]
edition = "2021"
name = "lang_handler"
version = "0.0.0"

[lib]
name = "lang_handler"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
bytes = "1.10.1"
regex = "1.11.1"
url = "2.5.4"
