#!/usr/bin/env bash

printf "amqp"
printf ",apcu"
# printf ",ast"
printf ",bcmath"
printf ",bz2"
printf ",calendar"
printf ",ctype"
printf ",curl"
printf ",dba"
# printf ",dio"
printf ",dom"
printf ",ds"
# printf ",enchant"
printf ",event"
printf ",exif"
# printf ",ffi"
printf ",fileinfo"
printf ",filter"
printf ",ftp"
printf ",gd"
printf ",gettext"
# printf ",glfw"
printf ",gmp"
# printf ",gmssl"
# printf ",grpc"
printf ",iconv"
printf ",igbinary"
# printf ",imagick"
# printf ",imap"
# printf ",inotify"
printf ",intl"
# printf ",ldap"
# printf ",libxml"
printf ",mbregex"
printf ",mbstring"
# printf ",mcrypt"
printf ",memcache"
# printf ",memcached"
# printf ",mongodb"
# printf ",msgpack"
printf ",mysqli"
printf ",mysqlnd"
# printf ",oci8"
printf ",opcache"
printf ",openssl"
# printf ",opentelemetry"
# printf ",parallel"
printf ",password-argon2"
# printf ",pcntl"
printf ",pdo"
printf ",pdo_mysql"
# printf ",pdo_pgsql"
printf ",pdo_sqlite"
# printf ",pdo_sqlsrv"
# printf ",pgsql"
printf ",phar"
printf ",posix"
# printf ",protobuf"
printf ",rar"
# printf ",rdkafka"
# printf ",readline"
printf ",redis"
printf ",session"
printf ",shmop"
printf ",simdjson"
printf ",simplexml"
# printf ",snappy"
printf ",soap"
# printf ",sockets"
# printf ",sodium"
# printf ",spx"
printf ",sqlite3"
printf ",sqlsrv"
# printf ",swoole"
# printf ",swoole-hook-mysql"
# printf ",swoole-hook-pgsql"
# printf ",swoole-hook-sqlite"
printf ",swow"
printf ",sysvmsg"
printf ",sysvsem"
printf ",sysvshm"
printf ",tidy"
printf ",tokenizer"
printf ",uuid"
# printf ",uv"
# printf ",xdebug"
printf ",xhprof"
# printf ",xlswriter"
printf ",xml"
printf ",xmlreader"
printf ",xmlwriter"
# printf ",xsl"
printf ",yac"
printf ",yaml"
printf ",zip"
printf ",zlib"
# printf ",zstd"
printf "\n"
